### ISSUE TITLE
Customize `/auth/sso` redirect behavior

### ISSUE THREAD

**Issue by RikyTres** [rishabhp/sso-rails-client#3]
It's not clear what happen when you call `/auth/sso`.

I'd like to pass a param to this route like this `/auth/sso?redirect_uri` with the aim of handle another level of redirection.

Let's see a concrete sample.
When I call `/auth/sso` I got redirected to `http://localhost:3000/auth/sso/authorize?client_id=key&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fsso%2Fcallback&response_type=code&state=394e6...`. As you can see this is the value of `redirect_uri` param: `http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fsso%2Fcallback`.

I need to add a param to this URI like this: `http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fsso%2Fcallback%3Fredirect_uri%3Dsome.url.com`. You can see the `?redirect_uri=some.url.com` param at the end.

I try to handle this overriding the request_phase on my custom strategy, but it doesn't work.

Is there a way to do that? Is there a manual that explain this kind of customization? (I followed this one http://codetheory.in/rails-devise-omniauth-sso/)

**Comment by rishabhp** [comment]
As I've mentioned I think it should be configurable. Don't remember looking into it. If not then at least try changing the gem's code and see if it works. Might have to read the gem's code a bit to figure out how to customise.

I don't think I'll get time to figure this out.

**Comment by RikyTres** [comment]
I hope it's something configurable, becouse I think is not a good thing change the gem's code.
